# Generated by Django 3.1 on 2022-01-21 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20220119_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunningServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('runningYN', models.BooleanField()),
            ],
        ),
    ]
