# Generated by Django 3.1 on 2022-01-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_runningservices_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='runningservices',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
