# Generated by Django 3.1 on 2022-03-10 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contentsid', models.CharField(max_length=30)),
                ('content', models.TextField(null=True)),
                ('order', models.IntegerField()),
                ('useYN', models.BooleanField(default='Y')),
            ],
        ),
    ]
